# Generated by Django 5.2 on 2025-04-14 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalentry',
            name='author',
        ),
    ]
